services:
  personal_site:
    build: .
    container_name: personal_site
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - "./core:/app"
    ports:
      - "8000:8000"
    environment:
      - SECRET_KEY=test
      - DEBUG=True