services:
  personal_site:
    build: .
    container_name: personal_site
    command: gunicorn core.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - "./core:/app"
      - static_volume:/app/static
      - media_volume:/app/media
    expose:
      - '8000'
    env_file:
      - .env

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - "443:443"
    volumes:
      - "./nginx.conf:/etc/nginx/conf.d/default.conf"
      - static_volume:/home/app/static
      - media_volume:/home/app/media
      - "./localhost.pem:/etc/ssl/certs/localhost.pem"
      - "./localhost-key.pem:/etc/ssl/private/localhost-key.pem"
    depends_on:
      - personal_site

volumes:
  static_volume:
  media_volume:
